
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&autoReconnect=true
      username: root
      password: start123
mybatis:
   mapperLocations: classpath:/mapper/*.xml
   configuration:
     map-underscore-to-camel-case: true